"""Alembic migration environment (DESIGN §5.2 plumbing).

Alembic executes this file on *every* command — including ``revision
--autogenerate``, which migrates nothing but needs the models and the database.
It sets up the run context and hands off to ``context.run_migrations()``; the
schema changes themselves live in ``versions/``.

Wires Alembic to the application's SQLAlchemy :class:`~app.core.db.Base` and
reads ``DATABASE_URL`` from the app config (NFR-MAINT-04), not from
``alembic.ini`` — no connection string is hardcoded.

Generated by ``alembic init`` and hand-maintained since — unlike a revision
file, this one is meant to be edited.
"""

from logging.config import fileConfig

from alembic import context
from sqlalchemy import create_engine
from sqlalchemy.pool import NullPool

# Load-bearing despite looking unused: importing each module registers its tables
# on ``Base.metadata``. Drop these and ``--autogenerate`` sees empty metadata, so
# it emits a DROP for every existing table.
import app.films.models
import app.genres.models
import app.ratings.models
import app.tags.models  # noqa: F401  (imported for the side effect, not the name)
from app.core.config import get_settings
from app.core.db import Base

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Passed directly to ``create_engine`` rather than stashed via
# ``config.set_main_option`` — Alembic's ConfigParser treats ``%`` as
# interpolation syntax and would choke on a percent-encoded password.

target_metadata = Base.metadata


def run_migrations_offline() -> None:
    """Print the SQL instead of executing it (``--sql``), for review and hand-off
    where the app has no DDL access."""
    context.configure(
        url=get_settings().database_url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Execute the migrations against a live connection."""
    # NullPool: this process runs one migration and exits, so a connection pool
    # would only leave idle connections behind.
    connectable = create_engine(get_settings().database_url, poolclass=NullPool)
    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
